import svgArrowDown from '../../assets/svgs/arrow_down.svg';
import svgBadgeCrown from '../../assets/svgs/badge_crown.svg';
import svgBell from '../../assets/svgs/bell.svg';
import svgCheck from '../../assets/svgs/check.svg';
import svgChevronsLeft from '../../assets/svgs/chevrons_left.svg';
import svgCrown from '../../assets/svgs/crown.svg';
import svgFeedCreatePopupClose from '../../assets/svgs/feed_create_popup_close.svg';
import svgKey from '../../assets/svgs/key.svg';
import svgLeftAngleBracket from '../../assets/svgs/left_angle_bracket.svg';
import svgLock from '../../assets/svgs/lock.svg';
import svgLogo from '../../assets/svgs/logo.svg';
import svgMail from '../../assets/svgs/mail.svg';
import svgMenu from '../../assets/svgs/menu.svg';
import svgMinusCircle from '../../assets/svgs/minus_circle.svg';
import svgPlus from '../../assets/svgs/plus.svg';
import svgPlusCircle from '../../assets/svgs/plus_circle.svg';
import svgPlusGray20 from '../../assets/svgs/plus_gray20.svg';
import svgRightAngleBracket from '../../assets/svgs/right_angle_bracket.svg';
import svgSearch from '../../assets/svgs/search.svg';
import svgSmallRightAngleBracket from '../../assets/svgs/small_right_angle_bracket.svg';
import svgTrashCan from '../../assets/svgs/trash_can.svg';
import svgUploadClose from '../../assets/svgs/upload_close.svg';
import svgUploadPlus from '../../assets/svgs/upload_plus.svg';

export const SvgCheck = svgCheck;
export const SvgKey = svgKey;
export const SvgLogo = svgLogo;
export const SvgMail = svgMail;
export const SvgArrowDown = svgArrowDown;
export const SvgTrashcan = svgTrashCan;
export const SvgBadgeCrown = svgBadgeCrown;
export const SvgUploadPlus = svgUploadPlus;
export const SvgUploadClose = svgUploadClose;
export const SvgLeftAngleBracket = svgLeftAngleBracket;
export const SvgRightAngleBracket = svgRightAngleBracket;
export const SvgLock = svgLock;
export const SvgCrown = svgCrown;
export const SvgFeedCreatePopupClose  = svgFeedCreatePopupClose;
export const SvgMinusCircle = svgMinusCircle;
export const SvgPlusCircle = svgPlusCircle;
export const SvgChevronsLeft = svgChevronsLeft;
export const SvgMenu = svgMenu;
export const SvgPlus = svgPlus;
export const SvgSearch = svgSearch;
export const SvgBell = svgBell;
export const SvgSmallRightAngleBracket = svgSmallRightAngleBracket;
export const SvgPlusGray20 = svgPlusGray20;
