import svgArrowDown from '../../assets/svgs/arrow_down.svg';
import svgBadgeCrown from '../../assets/svgs/badge_crown.svg';
import svgCheck from '../../assets/svgs/check.svg';
import svgCrown from '../../assets/svgs/crown.svg';
import svgKey from '../../assets/svgs/key.svg';
import svgLeftAngleBracket from '../../assets/svgs/left_angle_bracket.svg';
import svgLock from '../../assets/svgs/lock.svg';
import svgLogo from '../../assets/svgs/logo.svg';
import svgMail from '../../assets/svgs/mail.svg';
import svgRightAngleBracket from '../../assets/svgs/right_angle_bracket.svg';
import svgTrashCan from '../../assets/svgs/trash_can.svg';
import svgUploadClose from '../../assets/svgs/upload_close.svg';
import svgUploadPlus from '../../assets/svgs/upload_plus.svg';

export const SvgCheck = svgCheck;
export const SvgKey = svgKey;
export const SvgLogo = svgLogo;
export const SvgMail = svgMail;
export const SvgArrowDown = svgArrowDown;
export const SvgTrashcan = svgTrashCan;
export const SvgBadgeCrown = svgBadgeCrown;
export const SvgUploadPlus = svgUploadPlus;
export const SvgUploadClose = svgUploadClose;
export const SvgLeftAngleBracket = svgLeftAngleBracket;
export const SvgRightAngleBracket = svgRightAngleBracket;
export const SvgLock = svgLock;
export const SvgCrown = svgCrown;